import type { Metadata } from 'next';
import Link from 'next/link';
import { LegalLayout, Section, greenHi } from '@/components/legal/legal-layout';

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'How Sunday Huddle collects, uses, stores, and shares information for accounts, pools, picks, and payments.',
};

const EFFECTIVE_DATE = 'August 27, 2026';
const LAST_UPDATED = 'August 27, 2026';

const toc = [
  { id: 'introduction', label: 'Introduction' },
  { id: 'information-we-collect', label: 'Information We Collect' },
  { id: 'how-we-use-information', label: 'How We Use Information' },
  { id: 'how-information-is-shared', label: 'How Information Is Shared' },
  { id: 'pool-participant-info', label: 'Pool and Participant Information' },
  { id: 'cookies', label: 'Cookies and Similar Technologies' },
  { id: 'third-party-services', label: 'Third-Party Services' },
  { id: 'data-retention', label: 'Data Retention' },
  { id: 'data-security', label: 'Data Security' },
  { id: 'account-deletion', label: 'Account Deletion and Data Requests' },
  { id: 'childrens-privacy', label: "Children's Privacy" },
  { id: 'state-privacy-rights', label: 'U.S. State Privacy Rights' },
  { id: 'international-users', label: 'International Users' },
  { id: 'changes', label: 'Changes to This Policy' },
  { id: 'contact', label: 'Contact' },
];

export default function PrivacyPage() {
  return (
    <LegalLayout
      breadcrumbCurrent="Privacy Policy"
      eyebrow="Legal"
      title="Privacy Policy"
      effectiveDate={EFFECTIVE_DATE}
      lastUpdated={LAST_UPDATED}
      intro={
        <p>
          This Privacy Policy describes how Sunday Huddle collects, uses, stores, and shares information when you use
          our confidence pool, Pick&rsquo;em, and Survivor pool software.
        </p>
      }
      toc={toc}
    >
      <Section id="introduction" number={1} title="Introduction">
        <p>
          This Privacy Policy explains what information Sunday Huddle (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or
          &ldquo;our&rdquo;) collects through the Sunday Huddle website and application (the &ldquo;Service&rdquo;),
          how we use and share it, and the choices available to you. It should be read together with our{' '}
          <Link href="/terms" style={{ color: greenHi }}>Terms of Service</Link>.
        </p>
      </Section>

      <Section id="information-we-collect" number={2} title="Information We Collect">
        <p style={{ fontWeight: 700 }}>Information you provide</p>
        <ul style={{ margin: 0, paddingLeft: '1.25rem', display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
          <li>Account information: your name, email address, and password (stored as a secure hash, never in plain text) if you register with email/password;</li>
          <li>If you sign in with Google: your name and email address as provided by Google, and, where available, a profile photo;</li>
          <li>Pool information a commissioner enters: pool names, pool settings (such as tie-breaker rules and privacy settings), and a pool logo image URL, if set;</li>
          <li>Participant information: the name and, optionally, email address of each participant added to a pool, entered by the commissioner or the participant;</li>
          <li>Picks and tie-breaker answers submitted for a pool;</li>
          <li>Notification preferences (for example, whether you want pick reminder or product update emails); and</li>
          <li>Anything else you choose to type into the Service, such as pool descriptions.</li>
        </ul>
        <p style={{ fontWeight: 700 }}>Information collected automatically</p>
        <ul style={{ margin: 0, paddingLeft: '1.25rem', display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
          <li>Authentication/session information needed to keep you signed in (see <a href="#cookies" style={{ color: greenHi }}>Cookies and Similar Technologies</a> below);</li>
          <li>Basic request and error log information generated by our hosting and database providers in the ordinary course of operating the Service; and</li>
          <li>Rate-limiting information (such as an IP address or account identifier and a request count) used briefly to detect and slow down brute-force login, password reset, and account-creation attempts.</li>
        </ul>
        <p>
          We do not currently use third-party analytics or advertising trackers, so we do not collect the kind of
          detailed browsing/device analytics such tools typically gather.
        </p>
        <p style={{ fontWeight: 700 }}>Payment information</p>
        <p>
          Payment for the Standard plan and add-on pools is processed by Stripe. We do not collect or store your full
          card number, expiration date, or security code — Stripe collects that directly through its own
          hosted/tokenized checkout. We store limited information about a completed purchase (such as the product
          purchased, quantity, amount, currency, status, and Stripe&rsquo;s own identifiers for the transaction) so we
          can display your purchase history and apply the correct plan to your account.
        </p>
      </Section>

      <Section id="how-we-use-information" number={3} title="How We Use Information">
        <p>We use the information described above to:</p>
        <ul style={{ margin: 0, paddingLeft: '1.25rem', display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
          <li>Provide, operate, and maintain the Service, including creating and managing pools, picks, and standings;</li>
          <li>Authenticate you and keep your account secure;</li>
          <li>Process Standard plan and add-on pool purchases, and apply the resulting entitlements to your account;</li>
          <li>Send transactional emails, such as pick reminders, weekly summaries, purchase confirmations, and account-related notices (for example, password reset or deletion-confirmation emails);</li>
          <li>Detect, prevent, and respond to fraud, abuse, and security incidents;</li>
          <li>Debug and improve the Service; and</li>
          <li>Comply with our legal obligations.</li>
        </ul>
      </Section>

      <Section id="how-information-is-shared" number={4} title="How Information Is Shared">
        <p>
          We do not sell your personal information. We share information only with the service providers necessary
          to operate Sunday Huddle, and only to the extent needed for them to provide their service to us:
        </p>
        <ul style={{ margin: 0, paddingLeft: '1.25rem', display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
          <li><strong>Stripe</strong> (payment processing) — receives the information needed to process a purchase;</li>
          <li><strong>Google</strong> (authentication) — provides your name/email back to us if you sign in with Google;</li>
          <li><strong>Supabase</strong> (database hosting and Google sign-in exchange) — stores the account, pool, and pick data described above;</li>
          <li><strong>Vercel</strong> (application hosting) — runs the Service and its server-side logic;</li>
          <li><strong>Upstash</strong> (rate-limiting) — briefly processes an identifier (such as an email or IP address) to detect abusive request patterns; and</li>
          <li>Our email delivery provider — sends the transactional emails described above on our behalf.</li>
        </ul>
        <p>
          We may also disclose information if required to do so by law, or in connection with a merger, acquisition,
          or sale of assets, subject to this Policy continuing to apply to information already collected.
        </p>
      </Section>

      <Section id="pool-participant-info" number={5} title="Pool and Participant Information">
        <p>
          Sunday Huddle is built around shared pools, so information entered into a pool is not purely private to the
          person who entered it:
        </p>
        <ul style={{ margin: 0, paddingLeft: '1.25rem', display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
          <li>The commissioner who administers a pool can see the names, email addresses (if provided), and picks of every participant in that pool, and can manage or override that data.</li>
          <li>Other participants in the same pool can typically see your name and your picks/standings once they are revealed, as part of that pool&rsquo;s leaderboard — this is inherent to how a shared pool works.</li>
          <li>If a commissioner marks a pool private, a password is required to view that pool&rsquo;s picks, standings, or results at all; this restricts outside access to the pool, but does not hide participant information from other participants who already have the pool&rsquo;s password.</li>
        </ul>
        <p>
          We do not represent participant information as private from the commissioner of a pool a participant has
          joined, since the Service gives commissioners administrative access to their own pool&rsquo;s data by
          design.
        </p>
      </Section>

      <Section id="cookies" number={6} title="Cookies and Similar Technologies">
        <p>We use a small number of cookies, all of which are essential to operating the Service:</p>
        <ul style={{ margin: 0, paddingLeft: '1.25rem', display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
          <li><strong>Session cookie</strong> — an HttpOnly cookie that keeps a commissioner/admin signed in, valid for up to 90 days;</li>
          <li><strong>Sign-in handoff cookie</strong> — a short-lived (about one minute) cookie used only to hand your session from our Google sign-in redirect to your browser; it is deleted automatically the next time the page loads;</li>
          <li><strong>OAuth flow cookies</strong> — short-lived (a few minutes) cookies that keep track of your sign-in/registration flow while you are redirected to and back from Google;</li>
          <li><strong>Private-pool access cookie</strong> — a pool-specific, signed cookie set after you correctly enter a private pool&rsquo;s password, valid for up to 30 days, so you are not asked for the password on every visit to that pool; and</li>
          <li><strong>Cookie notice cookie</strong> — remembers your choice on our cookie notice (see below) for up to one year, so it does not show again on every visit.</li>
        </ul>
        <p>
          Our cookie notice, shown on your first visit, explains that these cookies are required and links back to
          this section; you can reopen it at any time from the &ldquo;Cookie Preferences&rdquo; link in the footer.
          Because every cookie above is required for the Service to function, there is currently nothing optional to
          turn on or off.
        </p>
        <p>
          We also use your browser&rsquo;s local storage (not a cookie) to keep you signed in between visits, to
          remember a participant&rsquo;s pick session on a shared device for up to 24 hours, and to locally cache
          in-progress picks before they are submitted. We do not currently use analytics or advertising cookies or
          similar tracking technologies.
        </p>
      </Section>

      <Section id="third-party-services" number={7} title="Third-Party Services">
        <p>
          The third-party providers listed in <a href="#how-information-is-shared" style={{ color: greenHi }}>How Information Is Shared</a>{' '}
          each process information under their own privacy policies:
        </p>
        <ul style={{ margin: 0, paddingLeft: '1.25rem', display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
          <li>Stripe — <a href="https://stripe.com/privacy" target="_blank" rel="noopener noreferrer" style={{ color: greenHi }}>stripe.com/privacy</a></li>
          <li>Google — <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" style={{ color: greenHi }}>policies.google.com/privacy</a></li>
          <li>Supabase — <a href="https://supabase.com/privacy" target="_blank" rel="noopener noreferrer" style={{ color: greenHi }}>supabase.com/privacy</a></li>
          <li>Vercel — <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer" style={{ color: greenHi }}>vercel.com/legal/privacy-policy</a></li>
          <li>Upstash — <a href="https://upstash.com/privacy" target="_blank" rel="noopener noreferrer" style={{ color: greenHi }}>upstash.com/privacy</a></li>
        </ul>
        <p>
          We also retrieve NFL schedule, team, and score information from ESPN&rsquo;s public sports data (with a
          secondary sports-data provider used as a fallback) to score picks. This is public sports data, not personal
          information about you.
        </p>
      </Section>

      <Section id="data-retention" number={8} title="Data Retention">
        <p>
          We do not currently operate a fixed, automatic retention schedule for every category of data. We retain
          information for as long as reasonably necessary to provide the Service to you, comply with our legal
          obligations, resolve disputes, and enforce our agreements. When you delete your commissioner account, we
          delete your account profile and sign-in access as described in{' '}
          <a href="#account-deletion" style={{ color: greenHi }}>Account Deletion and Data Requests</a> below; pools
          you created are archived rather than deleted, so the historical picks, scores, and standings your
          participants earned are preserved. When a specific pool is deleted (rather than an account), that pool and
          its participants, picks, scores, and tie-breaker data are permanently removed.
        </p>
      </Section>

      <Section id="data-security" number={9} title="Data Security">
        <p>
          We use reasonable administrative, technical, and organizational safeguards designed to protect your
          information, including password hashing, encrypted/signed access tokens for private pools, and access
          controls limiting who can read or change account, pool, and payment data. No method of transmission or
          storage is completely secure, and we cannot guarantee absolute security of your information.
        </p>
      </Section>

      <Section id="account-deletion" number={10} title="Account Deletion and Data Requests">
        <p>
          Commissioners can request deletion of their account from Account Settings. We send a confirmation link to
          your account email that must be used within 24 hours to complete the deletion. Once confirmed, your
          profile, sign-in access, and account settings are permanently deleted. Pools you created are archived
          (deactivated) rather than deleted, so that historical picks, scores, and standings your participants earned
          are preserved for them, even though the pool is no longer active or visible from your (deleted) account.
        </p>
        <p>
          Participants do not currently have a self-service way to delete their own participant record from within
          the Service; a participant who wants their name, email, or picks removed from a pool should contact the
          pool&rsquo;s commissioner, or reach us at <strong>[PRIVACY CONTACT EMAIL]</strong> and we will assist.
        </p>
      </Section>

      <Section id="childrens-privacy" number={11} title="Children's Privacy">
        <p>
          Sunday Huddle is not directed to children under the age of 13, and we do not knowingly collect personal
          information from children under 13. If you believe a child under 13 has provided us with personal
          information, contact us at <strong>[PRIVACY CONTACT EMAIL]</strong> so we can delete it.
        </p>
      </Section>

      <Section id="state-privacy-rights" number={12} title="U.S. State Privacy Rights">
        <p>
          Depending on where you live, you may have rights under applicable U.S. state privacy laws, which can
          include the right to know what personal information we hold about you, request correction of inaccurate
          information, request deletion of your information, request a portable copy of your information, and opt out
          of certain uses of your information (such as targeted advertising or the sale of personal information — we
          do not engage in either). Where these rights apply to you, you can exercise them by contacting us at{' '}
          <strong>[PRIVACY CONTACT EMAIL]</strong>. We do not claim compliance with any specific state privacy law
          beyond what applies to us as a matter of law; this section will be updated as our practices and applicable
          obligations are confirmed.
        </p>
      </Section>

      <Section id="international-users" number={13} title="International Users">
        <p>
          Sunday Huddle is operated from the United States, and information we collect is generally processed and
          stored there. If you access the Service from outside the United States, your information will be
          transferred to, stored, and processed in the United States (and any other country where our service
          providers operate), which may have different data protection laws than your country of residence. We do
          not currently claim compliance with the EU General Data Protection Regulation (GDPR) or other non-U.S.
          privacy frameworks.
        </p>
      </Section>

      <Section id="changes" number={14} title="Changes to This Policy">
        <p>
          We may update this Privacy Policy from time to time. If we make a material change, we will update the
          &ldquo;Last updated&rdquo; date above and, where appropriate, notify you by email or through the Service.
        </p>
      </Section>

      <Section id="contact" number={15} title="Contact">
        <p>
          Questions about this Privacy Policy, or requests regarding your information, can be sent to{' '}
          <strong>[PRIVACY CONTACT EMAIL]</strong>.
        </p>
      </Section>
    </LegalLayout>
  );
}

